name: noir_journal
description: "A Flutter application for journaling with a dark theme and minimalistic design."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  package_info_plus: ^8.3.0
  awesome_notifications: ^0.10.1
  app_settings: ^6.1.1
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  rename_app: ^1.6.3
  change_app_package_name: ^1.5.0
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/icon/foreground.png
    - assets/icon/background.png
    - assets/icon/icon.png

flutter_native_splash:
  color: "#000000"
  image: assets/icon/splash.png
  android: true
  ios: false
  web: false
  android_12:
    color: "#000000"
    image: assets/icon/splash.png
