name: noir_journal
description: "A Flutter application for journaling with a dark theme and minimalistic design."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  rename_app: ^1.6.3
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true
