name: noir_journal
description: "A Flutter application for journaling with a dark theme and minimalistic design."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  package_info_plus: ^8.3.0
  app_settings: ^6.1.1
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.2.4
  path_provider: ^2.1.5
  share_plus: ^11.0.0
  file_picker: ^10.2.0
  crypto: ^3.0.6
  fl_chart: ^1.0.0
  flutter_speed_dial: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  rename_app: ^1.6.3
  change_app_package_name: ^1.5.0
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/icon/foreground.png
    - assets/icon/background.png
    - assets/icon/icon.png

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-VariableFont_opsz,wght.ttf
        - asset: assets/fonts/inter/Inter-Italic-VariableFont_opsz,wght.ttf
          style: italic

    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/roboto/Roboto-Italic-VariableFont_wdth,wght.ttf
          style: italic

    - family: OpenSans
      fonts:
        - asset: assets/fonts/opensans/OpenSans-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/opensans/OpenSans-Italic-VariableFont_wdth,wght.ttf
          style: italic

    - family: Lato
      fonts:
        - asset: assets/fonts/lato/Lato-Regular.ttf
        - asset: assets/fonts/lato/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/lato/Lato-Italic.ttf
          style: italic
        - asset: assets/fonts/lato/Lato-BoldItalic.ttf
          weight: 700
          style: italic

    - family: SourceSans3
      fonts:
        - asset: assets/fonts/sourcesans/SourceSans3-VariableFont_wght.ttf
        - asset: assets/fonts/sourcesans/SourceSans3-Italic-VariableFont_wght.ttf
          style: italic

    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-VariableFont_wght.ttf
        - asset: assets/fonts/nunito/Nunito-Italic-VariableFont_wght.ttf
          style: italic

flutter_native_splash:
  color: "#000000"
  image: assets/icon/splash.png
  android: true
  ios: false
  web: false
  android_12:
    color: "#000000"
    image: assets/icon/splash.png
