import 'package:flutter/material.dart';

class DiaryIcons {
  static final List<IconData> all = [
    // Daily Life & Essentials
    Icons.book_rounded,
    Icons.favorite_rounded,
    Icons.star_rounded,
    Icons.lightbulb_rounded,
    Icons.lock_rounded,
    Icons.coffee_rounded,
    Icons.nightlight_round,
    Icons.emoji_emotions_rounded,
    Icons.wb_sunny_rounded,
    Icons.alarm_rounded,
    Icons.bed_rounded,
    Icons.shower_rounded,
    Icons.kitchen_rounded,
    Icons.local_laundry_service_rounded,
    Icons.clean_hands_rounded,

    // Emotions & Feelings
    Icons.celebration_rounded,
    Icons.psychology_rounded,
    Icons.favorite_border_rounded,
    Icons.sentiment_very_satisfied_rounded,
    Icons.sentiment_satisfied_rounded,
    Icons.sentiment_neutral_rounded,
    Icons.sentiment_dissatisfied_rounded,
    Icons.auto_awesome_rounded,
    Icons.mood_rounded,
    Icons.face_rounded,

    // Activities & Hobbies
    Icons.palette_rounded,
    Icons.music_note_rounded,
    Icons.headphones_rounded,
    Icons.piano_rounded,
    Icons.mic_rounded,
    Icons.theater_comedy_rounded,
    Icons.movie_rounded,
    Icons.tv_rounded,
    Icons.videogame_asset_rounded, Icons.casino_rounded,
    Icons.sports_esports_rounded,
    Icons.games_rounded,

    // Travel & Transportation
    Icons.flight_rounded,
    Icons.directions_run_rounded,
    Icons.directions_bike_rounded,
    Icons.directions_car_rounded,
    Icons.directions_boat_rounded,
    Icons.directions_bus_rounded,
    Icons.directions_railway_rounded,
    Icons.directions_walk_rounded,
    Icons.flight_takeoff_rounded,
    Icons.flight_land_rounded,
    Icons.train_rounded,
    Icons.subway_rounded,
    Icons.motorcycle_rounded,
    Icons.taxi_alert_rounded,
    Icons.map_rounded,
    Icons.luggage_rounded,

    // Food & Dining
    Icons.restaurant_rounded,
    Icons.fastfood_rounded,
    Icons.cake_rounded,
    Icons.local_pizza_rounded,
    Icons.local_cafe_rounded,
    Icons.local_bar_rounded,
    Icons.wine_bar_rounded,
    Icons.breakfast_dining_rounded,
    Icons.lunch_dining_rounded,
    Icons.dinner_dining_rounded,
    Icons.icecream_rounded,
    Icons.emoji_food_beverage_rounded,
    Icons.local_dining_rounded,
    Icons.bakery_dining_rounded,

    // Nature & Weather
    Icons.park_rounded,
    Icons.local_florist_rounded,
    Icons.nature_people_rounded,
    Icons.umbrella_rounded,
    Icons.beach_access_rounded,
    Icons.wb_cloudy_rounded,
    Icons.ac_unit_rounded,
    Icons.wb_twilight_rounded,
    Icons.forest_rounded,
    Icons.grass_rounded,
    Icons.landscape_rounded,
    Icons.water_drop_rounded, Icons.thunderstorm_rounded,
    Icons.wb_incandescent_rounded,

    // Work & Education
    Icons.work_rounded,
    Icons.school_rounded,
    Icons.science_rounded,
    Icons.business_rounded,
    Icons.laptop_rounded,
    Icons.computer_rounded,
    Icons.phone_rounded,
    Icons.email_rounded,
    Icons.meeting_room_rounded,
    Icons.assignment_rounded,
    Icons.calculate_rounded,
    Icons.engineering_rounded,
    Icons.medical_services_rounded,
    Icons.construction_rounded,

    // Health & Wellness
    Icons.spa_rounded,
    Icons.self_improvement_rounded,
    Icons.fitness_center_rounded,
    Icons.local_hospital_rounded,
    Icons.healing_rounded,
    Icons.medication_rounded,
    Icons.psychology_alt_rounded,
    Icons.volunteer_activism_rounded,
    Icons.accessibility_new_rounded,
    Icons.pregnant_woman_rounded,

    // Family & Relationships
    Icons.family_restroom_rounded,
    Icons.child_friendly_rounded,
    Icons.elderly_rounded,
    Icons.people_rounded, Icons.group_rounded,
    Icons.person_rounded,
    Icons.child_care_rounded,
    Icons.baby_changing_station_rounded,

    // Sports & Fitness
    Icons.sports_soccer_rounded,
    Icons.sports_basketball_rounded,
    Icons.sports_tennis_rounded,
    Icons.sports_esports_rounded,
    Icons.sports_golf_rounded,
    Icons.sports_mma_rounded,
    Icons.sports_handball_rounded,
    Icons.sports_volleyball_rounded,
    Icons.sports_football_rounded,
    Icons.sports_hockey_rounded,
    Icons.sports_cricket_rounded,
    Icons.sports_baseball_rounded,
    Icons.sports_rugby_rounded,
    Icons.sports_kabaddi_rounded,
    Icons.sports_motorsports_rounded,
    Icons.sports_bar_rounded,
    Icons.sports_gymnastics_rounded,
    Icons.sports,
    Icons.pool_rounded,
    Icons.downhill_skiing_rounded,
    Icons.snowboarding_rounded,
    Icons.surfing_rounded,
    Icons.kitesurfing_rounded,

    // Shopping & Finance
    Icons.shopping_cart_rounded,
    Icons.attach_money_rounded,
    Icons.credit_card_rounded,
    Icons.account_balance_rounded,
    Icons.savings_rounded,
    Icons.shopping_bag_rounded,
    Icons.store_rounded,
    Icons.local_grocery_store_rounded,
    Icons.local_mall_rounded,
    Icons.receipt_long_rounded,

    // Technology & Gadgets
    Icons.camera_alt_rounded,
    Icons.photo_camera_rounded,
    Icons.videocam_rounded,
    Icons.smartphone_rounded,
    Icons.tablet_rounded,
    Icons.watch_rounded,
    Icons.headset_rounded,
    Icons.speaker_rounded,
    Icons.memory_rounded,
    Icons.router_rounded,

    // Pets & Animals
    Icons.pets_rounded,
    Icons.cruelty_free_rounded,

    // Special Occasions
    Icons.celebration_outlined,
    Icons.party_mode_rounded,
    Icons.card_giftcard_rounded,
    Icons.local_florist_outlined,
    Icons.event_rounded,
    Icons.today_rounded,
    Icons.calendar_month_rounded,
    Icons.schedule_rounded,

    // Creative & Artistic
    Icons.brush_rounded,
    Icons.color_lens_rounded,
    Icons.draw_rounded,
    Icons.edit_rounded,
    Icons.create_rounded,
    Icons.photo_rounded,
    Icons.camera_enhance_rounded,
    Icons.auto_fix_high_rounded,

    // Miscellaneous
    Icons.star_border_rounded,
    Icons.bookmark_rounded,
    Icons.flag_rounded,
    Icons.push_pin_rounded,
    Icons.label_rounded, Icons.local_offer_rounded,
    Icons.star_purple500_rounded,
    Icons.extension_rounded,
    Icons.verified_rounded,
    Icons.workspace_premium_rounded,
  ];
}
